spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: qwerty
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080
